INSERT INTO SPECIALTY (NAME) VALUES ('Dermatology');
INSERT INTO SPECIALTY (NAME) VALUES ('Ophthalmology');
INSERT INTO SPECIALTY (NAME) VALUES ('Radiology');
INSERT INTO SPECIALTY (NAME) VALUES ('Family Medicine');
INSERT INTO SPECIALTY (NAME) VALUES ('Pediatrics');

INSERT INTO PATIENT (NAME, AGE) VALUES ('Manuel', 53);
INSERT INTO PATIENT (NAME, AGE) VALUES ('Joana', 32);
INSERT INTO PATIENT (NAME, AGE) VALUES ('Ana', 25);
INSERT INTO PATIENT (NAME, AGE) VALUES ('Diogo', 33);
INSERT INTO PATIENT (NAME, AGE) VALUES ('Catarina', 33);
INSERT INTO PATIENT (NAME, AGE) VALUES ('Miguel', 40);

INSERT INTO PATHOLOGY (NAME) VALUES ('Pathology 1');
INSERT INTO PATHOLOGY (NAME) VALUES ('Pathology 2');
INSERT INTO PATHOLOGY (NAME) VALUES ('Pathology 3');
INSERT INTO PATHOLOGY (NAME) VALUES ('Pathology 4');
INSERT INTO PATHOLOGY (NAME) VALUES ('Pathology 5');
INSERT INTO PATHOLOGY (NAME) VALUES ('Pathology 6');
INSERT INTO PATHOLOGY (NAME) VALUES ('Pathology 7');

INSERT INTO SYMPTOM (DESCRIPTION) VALUES ('Symptom 1 Description');
INSERT INTO SYMPTOM (DESCRIPTION) VALUES ('Symptom 2 Description');
INSERT INTO SYMPTOM (DESCRIPTION) VALUES ('Symptom 3 Description');
INSERT INTO SYMPTOM (DESCRIPTION) VALUES ('Symptom 4 Description');
INSERT INTO SYMPTOM (DESCRIPTION) VALUES ('Symptom 5 Description');
INSERT INTO SYMPTOM (DESCRIPTION) VALUES ('Symptom 6 Description');
INSERT INTO SYMPTOM (DESCRIPTION) VALUES ('Symptom 7 Description');
INSERT INTO SYMPTOM (DESCRIPTION) VALUES ('Symptom 8 Description');
INSERT INTO SYMPTOM (DESCRIPTION) VALUES ('Symptom 9 Description');
INSERT INTO SYMPTOM (DESCRIPTION) VALUES ('Symptom 10 Description');
INSERT INTO SYMPTOM (DESCRIPTION) VALUES ('Symptom 11 Description');
INSERT INTO SYMPTOM (DESCRIPTION) VALUES ('Symptom 12 Description');
INSERT INTO SYMPTOM (DESCRIPTION) VALUES ('Symptom 13 Description');
INSERT INTO SYMPTOM (DESCRIPTION) VALUES ('Symptom 14 Description');
INSERT INTO SYMPTOM (DESCRIPTION) VALUES ('Symptom 15 Description');

INSERT INTO DOCTOR (NAME, SPECIALTY_ID) VALUES ('Antonio', 1);
INSERT INTO DOCTOR (NAME, SPECIALTY_ID) VALUES ('Maria', 2);
INSERT INTO DOCTOR (NAME, SPECIALTY_ID) VALUES ('Carlos', 3);
INSERT INTO DOCTOR (NAME, SPECIALTY_ID) VALUES ('Gabriela', 4);
INSERT INTO DOCTOR (NAME, SPECIALTY_ID) VALUES ('Paulo', 5);

INSERT INTO APPOINTMENT (DOCTOR_ID, PATIENT_ID, PATHOLOGY_ID) VALUES (1, 1, 1);
INSERT INTO APPOINTMENT (DOCTOR_ID, PATIENT_ID, PATHOLOGY_ID) VALUES (1, 1, 2);
INSERT INTO APPOINTMENT (DOCTOR_ID, PATIENT_ID, PATHOLOGY_ID) VALUES (2, 1, 3);
INSERT INTO APPOINTMENT (DOCTOR_ID, PATIENT_ID, PATHOLOGY_ID) VALUES (1, 2, 3);
INSERT INTO APPOINTMENT (DOCTOR_ID, PATIENT_ID, PATHOLOGY_ID) VALUES (3, 3, 4);
INSERT INTO APPOINTMENT (DOCTOR_ID, PATIENT_ID, PATHOLOGY_ID) VALUES (4, 4, 5);
INSERT INTO APPOINTMENT (DOCTOR_ID, PATIENT_ID, PATHOLOGY_ID) VALUES (5, 5, 6);
INSERT INTO APPOINTMENT (DOCTOR_ID, PATIENT_ID, PATHOLOGY_ID) VALUES (2, 6, 7);

INSERT INTO APPOINTMENT_SYMPTOM (APPOINTMENT_ID, SYMPTOM_ID) VALUES (1, 1);
INSERT INTO APPOINTMENT_SYMPTOM (APPOINTMENT_ID, SYMPTOM_ID) VALUES (1, 2);
INSERT INTO APPOINTMENT_SYMPTOM (APPOINTMENT_ID, SYMPTOM_ID) VALUES (2, 3);
INSERT INTO APPOINTMENT_SYMPTOM (APPOINTMENT_ID, SYMPTOM_ID) VALUES (2, 4);
INSERT INTO APPOINTMENT_SYMPTOM (APPOINTMENT_ID, SYMPTOM_ID) VALUES (2, 5);
INSERT INTO APPOINTMENT_SYMPTOM (APPOINTMENT_ID, SYMPTOM_ID) VALUES (3, 6);
INSERT INTO APPOINTMENT_SYMPTOM (APPOINTMENT_ID, SYMPTOM_ID) VALUES (3, 7);
INSERT INTO APPOINTMENT_SYMPTOM (APPOINTMENT_ID, SYMPTOM_ID) VALUES (4, 6);
INSERT INTO APPOINTMENT_SYMPTOM (APPOINTMENT_ID, SYMPTOM_ID) VALUES (4, 7);
INSERT INTO APPOINTMENT_SYMPTOM (APPOINTMENT_ID, SYMPTOM_ID) VALUES (5, 8);
INSERT INTO APPOINTMENT_SYMPTOM (APPOINTMENT_ID, SYMPTOM_ID) VALUES (6, 9);
INSERT INTO APPOINTMENT_SYMPTOM (APPOINTMENT_ID, SYMPTOM_ID) VALUES (6, 10);
INSERT INTO APPOINTMENT_SYMPTOM (APPOINTMENT_ID, SYMPTOM_ID) VALUES (6, 11);
INSERT INTO APPOINTMENT_SYMPTOM (APPOINTMENT_ID, SYMPTOM_ID) VALUES (7, 12);
INSERT INTO APPOINTMENT_SYMPTOM (APPOINTMENT_ID, SYMPTOM_ID) VALUES (7, 13);
INSERT INTO APPOINTMENT_SYMPTOM (APPOINTMENT_ID, SYMPTOM_ID) VALUES (8, 14);
INSERT INTO APPOINTMENT_SYMPTOM (APPOINTMENT_ID, SYMPTOM_ID) VALUES (8, 15);

